# Mozilla User Preferences

/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 * For more information, see http://www.mozilla.org/unix/customizing.html#prefs
 */

user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1226004491);
user_pref("app.update.lastUpdateTime.background-update-timer", 1226004490);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1226004490);
user_pref("app.update.lastUpdateTime.microsummary-generator-update-timer", 1226004491);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1226004491);
user_pref("browser.cache.memory.capacity", 16384);
user_pref("browser.download.dir", "/home/neurostv/Desktop/Downloads");
user_pref("browser.download.folderList", 2);
user_pref("browser.download.manager.closeWhenDone", true);
user_pref("browser.history_expire_days.mirror", 180);
user_pref("browser.history_expire_days_min", 20);
user_pref("browser.migration.version", 1);
user_pref("browser.places.importBookmarksHTML", false);
user_pref("browser.places.importDefaults", false);
user_pref("browser.places.leftPaneFolderId", -1);
user_pref("browser.places.migratePostDataAnnotations", false);
user_pref("browser.places.smartBookmarksVersion", 1);
user_pref("browser.places.updateRecentTagsUri", false);
user_pref("browser.preferences.advanced.selectedTabIndex", 3);
user_pref("browser.safebrowsing.enabled", false);
user_pref("browser.safebrowsing.malware.enabled", false);
user_pref("browser.sessionstore.enabled", false);
user_pref("browser.sessionstore.resume_from_crash", false);
user_pref("browser.startup.homepage", "http://app.neuros.tv");
user_pref("browser.startup.homepage_override.mstone", "rv:1.9.0.3");
user_pref("browser.tabs.warnOnClose", false);
user_pref("browser.urlbar.matchOnlyTyped", true);
user_pref("browser.urlbar.maxRichResults", 0);
user_pref("content.notify.backoffcount", 5);
user_pref("extensions.autohide.bars.PersonalToolbar", false);
user_pref("extensions.autohide.bars.PersonalToolbar.always", false);
user_pref("extensions.autohide.bars.nav-bar", true);
user_pref("extensions.autohide.bars.nav-bar.always", false);
user_pref("extensions.autohide.bars.statBar", true);
user_pref("extensions.autohide.bars.statBar.always", false);
user_pref("extensions.autohide.bars.tabBar", true);
user_pref("extensions.autohide.bars.tabBar.always", false);
user_pref("extensions.autohide.bars.toolbar-menubar", false);
user_pref("extensions.autohide.bars.toolbar-menubar.always", false);
user_pref("extensions.autohide.closedFull", true);
user_pref("extensions.autohide.closedZombie", false);
user_pref("extensions.autohide.newFull", true);
user_pref("extensions.autohide.noContext", false);
user_pref("extensions.autohide.semiMode", false);
user_pref("extensions.autohide.statFloat", false);
user_pref("extensions.autohide.windowsTB", true);
user_pref("extensions.enabledItems", "{DD43485F-44CC-4452-A6C6-69356A7E33DA}:1.3.1,langpack-en-GB@firefox-3.0.ubuntu.com:3.0.3,ubufox@ubuntu.com:0.6,langpack-en-GB@xulrunner-1.9.ubuntu.com:1.9.0.3,{972ce4c6-7e08-4474-a285-3208198ce6fd}:3.0.3");
user_pref("extensions.lastAppVersion", "3.0.3");
user_pref("extensions.update.notifyUser", false);
user_pref("font.minimum-size.x-western", 15);
user_pref("font.size.fixed.x-western", 16);
user_pref("intl.charsetmenu.browser.cache", "UTF-8, ISO-8859-1");
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.dns.disableIPv6", true);
user_pref("network.http.pipelining", true);
user_pref("network.http.pipelining.maxrequests", 8);
user_pref("network.http.proxy.pipelining", true);
user_pref("nglayout.initialpaint.delay", 0);
user_pref("plugin.expose_full_path", true);
user_pref("pref.privacy.disable_button.view_cookies", false);
user_pref("privacy.item.offlineApps", true);
user_pref("spellchecker.dictionary", "en_US");
user_pref("ui.submenuDelay", 0);
user_pref("urlclassifier.keyupdatetime.https://sb-ssl.google.com/safebrowsing/newkey", 1228596493);
user_pref("xxx.legal.rights.seen", "0.0");
