#!/bin/bash

if ps ax | grep -v grep | grep -v dpkg | grep firefox > /dev/null
then
    echo "Killing Firefox so can write new profile"
    killall firefox
    sleep 4
fi


case "$1" in
	configure)
	;;

	install)
		echo "Running preinst on INSTALL"
	;;

	upgrade)
		echo "Running preinst on UPGRADE"
		if [ -e /home/neurostv/.mozilla ]; then
			echo "Found existing Mozilla, backing up user data."
			mkdir -p /tmp/mozilla-backups/
			cp -a /home/neurostv/.mozilla/firefox/zpoj64rl.default/bookmark* /tmp/mozilla-backups/
			cp -a /home/neurostv/.mozilla/firefox/zpoj64rl.default/sign* /tmp/mozilla-backups/
			cp -a /home/neurostv/.mozilla/firefox/zpoj64rl.default/key3.db /tmp/mozilla-backups/
		fi
	;;
esac
