#!/bin/bash

if ps ax | grep -v grep | grep firefox > /dev/null
then
  CONFIRMFIREFOXCLOSE=0
  if [ "$CONFIRMFIREFOXCLOSE" = "0" ]; then
    ### User confirmed - kill Firefox
    echo "Killing Firefox so can write new profile"
    killall firefox
    sleep 4
  else
    ### User canceled - stop script
    echo "Aborting"
    exit 0;
  fi
fi


case "$1" in
	configure)
	;;

	install)
		echo "Running preinst on INSTALL"
	;;

	upgrade)
		echo "Running preinst on UPGRADE"
		if [ -e /home/neurostv/.mozilla ]; then
			echo "Found existing Mozilla, backing up user data."
			mkdir -p /tmp/mozilla-backups/
			cp -a /home/neurostv/.mozilla/firefox/zpoj64rl.default/bookmarks.html /tmp/mozilla-backups/
			cp -a /home/neurostv/.mozilla/firefox/zpoj64rl.default/sign* /tmp/mozilla-backups/
			cp -a /home/neurostv/.mozilla/firefox/zpoj64rl.default/key3.db /tmp/mozilla-backups/
		fi
	;;
esac
